pagopa/cgn-onboarding-portal-backend

.gitignore, openapi/openapi.yaml, pom.xml
First draft of the OpenAPI descriptor for the portal
=> PE-48 - add openapi.yaml

src/main/java/it/gov/pagopa/cgn/portal/controller/AgreementController.java, src/main/java/it/gov/pagopa/cgn/portal/facade/DiscountFacade.java, src/main/java/it/gov/pagopa/cgn/portal/repository/DiscountRepository.java, src/main/java/it/gov/pagopa/cgn/portal/service/AgreementService.java, src/main/java/it/gov/pagopa/cgn/portal/service/AgreementServiceLight.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/AgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
- Implemented publish discount
Tested with testcontainers
=> PE-6: Implemented publish discount functionality

openapi/backoffice/openapi.yaml, pom.xml
Back-office APIs reside in their own descriptor.
=> PE-54 add back-office OpenAPI descriptor

src/main/java/it/gov/pagopa/cgn/portal/repository/DocumentRepository.java, src/test/java/it/gov/pagopa/cgn/portal/service/DocumentServiceTest.java
- Fixed delete document
Fixed bug on delete document
=> PE-11 Fixed delete document query and added missing test

.devops/code-review-pipelines.yml
Wait to merge we're finishing last configurations
=> Add sonarcloud config

src/main/java/it/gov/pagopa/cgn/portal/filestorage/AzureStorage.java, src/main/java/it/gov/pagopa/cgn/portal/util/CGNUtils.java
- Fixed error uploading image
Fixed error uploading image
Postman
=> Fixed upload image error

src/main/java/it/gov/pagopa/cgn/portal/config/ConfigProperties.java, src/main/java/it/gov/pagopa/cgn/portal/facade/DocumentFacade.java, src/main/java/it/gov/pagopa/cgn/portal/filestorage/AzureStorage.java, src/main/resources/application.properties, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/DocumentApiTest.java
{
"documentType": "agreement",
"documentUrl": "https://cgnportaltestdsa.blob.core.windows.net/userdocuments/3b68cb5f-b5ad-43da-9a3c-01aa1cb2eef5%2Fagreement.pdf?sv=2019-12-12&spr=https&se=2021-04-29T08%3A56%3A11Z&sr=b&sp=r&sig=%2FgmxMfJxoCbhGnR8u%2Bue4UHMt3M8qdJ96p6wXLI4zkc%3D"
}
=> PE-10 secure file download

src/main/resources/db/migration/R__create_online_merchant_materialized_view.sql
Add repeatable migration to create materialized view for online-merchant search API
The goal is to simplify the query on search API side,
applying some filtering in advance and denormalizing the data.
Tested together with search API development
=> PE-20 Setup materialized view online_merchant

email-templates/src/help-request.mjml, openapi/openapi.yaml, openapi/public.yaml, pom.xml, src/main/java/it/gov/pagopa/cgn/portal/controller/AgreementController.java, src/main/java/it/gov/pagopa/cgn/portal/controller/PublicApiController.java, src/main/java/it/gov/pagopa/cgn/portal/converter/help/HelpCategoryConverter.java, src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationFacade.java, src/main/java/it/gov/pagopa/cgn/portal/email/HelpRequestParams.java, src/main/java/it/gov/pagopa/cgn/portal/email/TemplateEmail.java, src/main/java/it/gov/pagopa/cgn/portal/security/WebSecurityConfig.java, src/main/java/it/gov/pagopa/cgn/portal/service/HelpService.java, src/main/resources/templates/email/help-request.html, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/HelpApiTest.java
- Add public help API 
- Add authenticated help API
- Send email help request
Add the ability for users to request some help.
Tested locally. Verified email template compliance.
=> PE-81 Add help API and send email help request

src/main/java/it/gov/pagopa/cgn/portal/util/CGNUtils.java
- Added check for valid upload image
- Deleted not used method
Postman
=> PE-95 Added check for valid upload image

email-templates/src/agreement-request-approved-both.mjml, src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationFacade.java, src/main/java/it/gov/pagopa/cgn/portal/email/TemplateEmail.java, src/main/java/it/gov/pagopa/cgn/portal/service/BackofficeAgreementService.java, src/main/resources/templates/email/agreement-request-approved-both.html, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/LogMemoryAppender.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeAgreementServiceTest.java
Send specific email notifications in case of Approved Agreement, based on Sales Channel type and Discount Code type
This change lets the merchant receive a more detailed and specific information about the next steps he has to perform
Tested on local machine. Validate email template rendering with an email service
=> PE-81 Send specific approved agreement email notification

src/main/java/it/gov/pagopa/cgn/portal/model/DiscountEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
- Fixed update discount without update any product
Bugfix on update discount with the same products
TestContainers and Postman
=> Fixed update discount with same products

src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationService.java, src/main/java/it/gov/pagopa/cgn/portal/email/EmailParams.java, src/main/java/it/gov/pagopa/cgn/portal/exception/CGNException.java, src/main/java/it/gov/pagopa/cgn/portal/filestorage/AzureStorage.java, src/main/java/it/gov/pagopa/cgn/portal/service/BackofficeAgreementService.java, src/main/java/it/gov/pagopa/cgn/portal/util/CGNUtils.java, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/exception/CGNExceptionTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/ProfileServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeAgreementServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/util/CGNUtilsTest.java
- Method getAgreements on backoffice side return now secure document URL
- Fixed check on document number on approveAgreement method
- Minor bugfix
Fixed some issue found testing backoffice API
Postman and TestContainers
=> Fixed backoffice documents API

src/main/java/it/gov/pagopa/cgn/portal/repository/BackofficeAgreementToValidateSpecification.java, src/main/java/it/gov/pagopa/cgn/portal/repository/CommonAgreementSpecification.java
- Fixed approved agreements query
Bugfix
Postman
=> Fixed approved agreements query

src/main/java/it/gov/pagopa/cgn/portal/service/AgreementService.java, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeApprovedAgreementServiceTest.java
- Show Suspended discounts on approved agreement detail on the Department side
Bugfix
on local machine
=> PE-129 Show Suspended discounts on approved agreement detail

src/main/java/it/gov/pagopa/cgn/portal/repository/DiscountRepository.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
- Added check to avoid that an agreement can publish more than 5 discounts
Bugfix
=> Max 5 discount can be published for agreement

src/main/java/it/gov/pagopa/cgn/portal/converter/backoffice/BackofficeAgreementConverter.java, src/main/java/it/gov/pagopa/cgn/portal/repository/BackofficeAgreementToValidateSpecification.java, src/main/java/it/gov/pagopa/cgn/portal/repository/CommonAgreementSpecification.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/backoffice/BackofficeAgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeAgreementServiceTest.java
- Fixed PE-119: now state filter should work as expected
Fix Bug PE-119
Tested with Postman
=> PE-119 - Fixed state filter

src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/java/it/gov/pagopa/cgn/portal/service/DocumentService.java, src/main/java/it/gov/pagopa/cgn/portal/service/ProfileService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/ProfileServiceTest.java
- Delete user documents if the merchant update the profile or one its discounts
Bugfix
Tested on local machine
=> PE-127 Delete uploaded documents on Draft agreement updates

src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
- Publishing a discount with future start date is now possible
TestContainer
=> PE-130 publish discount with data in the future

src/main/java/it/gov/pagopa/cgn/portal/interceptor/AgreementInterceptor.java, src/main/java/it/gov/pagopa/cgn/portal/security/JwtOperatorUser.java, src/main/java/it/gov/pagopa/cgn/portal/security/JwtTokenUtil.java, src/main/java/it/gov/pagopa/cgn/portal/util/CGNUtils.java, src/test/java/it/gov/pagopa/cgn/portal/security/JwtTokenUtilTest.java
- Fixed taxCode mapping for operator: now use company taxCode instead of user taxCode
Bugfix
Tested with TestContainer
=> Fixed taxcode mapping for operator

openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/DocumentConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/backoffice/BackofficeDocumentConverter.java, src/main/java/it/gov/pagopa/cgn/portal/model/DocumentEntity.java, src/test/java/it/gov/pagopa/cgn/portal/controller/DocumentApiTest.java
- Added document time to Document response
Bugfix
=> Added document time on Document response

src/main/java/it/gov/pagopa/cgn/portal/service/DocumentService.java, src/test/java/it/gov/pagopa/cgn/portal/controller/DocumentApiTest.java
Fix concurrency on document generation, given that Flying saucer is not thread safe (https://stackoverflow.com/a/12613266/15478227)
Bugfix
=> Fix concurrent document generation

src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
- Updating a suspended discount update status to Draft
- Cannot publish a suspended discount
Bugfix
Tested with TestContainer
=> PE-151 Updating a suspended discount change status to Draft

src/main/java/it/gov/pagopa/cgn/portal/service/AgreementService.java, src/main/java/it/gov/pagopa/cgn/portal/service/AgreementServiceLight.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/java/it/gov/pagopa/cgn/portal/service/DocumentService.java, src/main/java/it/gov/pagopa/cgn/portal/service/ProfileService.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/ProfileServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/UploadImageTest.java
- Updating profile, a discount or replacing the image of a rejected agreement, will also update the status of agreement to draft and reset some information
Bugfix
=> PE-160 Update rejected agreement update also status

src/main/java/it/gov/pagopa/cgn/portal/controller/AppServiceController.java, src/main/java/it/gov/pagopa/cgn/portal/security/WebSecurityConfig.java, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/controller/AppServerControllerTest.java
- Created an API with path "/" to App Service to avoid error on application insights. This API will be callable without authentication
Avoid failure in application insights caused by App Service Always ON call to "/" path
Tested with Postman
=> Added App Service controller over the path "/" to avoid error log

openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/backoffice/approved/BackofficeApprovedAgreementProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/CommonProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/ProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/model/AddressEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/DocumentService.java, src/main/resources/db/migration/V013__alter_address.sql, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/profile/CreateProfileApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/converter/profile/UpdateProfileConverterTest.java
- Collapsed multiple fields Address to only one
- Added Coordinates object into Address object inside open api specification
Tested with TestContainers and Postman
=> Single Field Address

openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/discount/DiscountConverter.java, src/test/java/it/gov/pagopa/cgn/portal/controller/discount/DiscountApiTest.java
- Added suspended reason message field to discount response
=> Added suspend reason message to Discount response

openapi/backoffice/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/controller/BackofficeAgreementController.java, src/main/java/it/gov/pagopa/cgn/portal/enums/BackofficeRequestSortColumnEnum.java, src/main/java/it/gov/pagopa/cgn/portal/filter/BackofficeFilter.java, src/main/java/it/gov/pagopa/cgn/portal/repository/BackofficeAgreementToValidateSpecification.java, src/main/java/it/gov/pagopa/cgn/portal/repository/CommonAgreementSpecification.java, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/backoffice/BackofficeAgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/ProfileServiceTest.java
- PE-111: Implemented custom ordering on Backoffice request tab
Implemented PE-111 task
Tested with TestContainers and Postman
=> PE-111 Implemented custom ordering on Backoffice request tab

src/main/resources/db/migration/V014__alter_address_coordinates.sql
- Migrated null coordinates to default value and updated column to not null
Fix already inserted null value for coordinates
=> Coordinates not null

openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/config/ConfigProperties.java, src/main/java/it/gov/pagopa/cgn/portal/config/WebMvConfig.java, src/main/java/it/gov/pagopa/cgn/portal/controller/GeolocationTokenController.java, src/main/resources/application.properties, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/GeolocationTokenApiTest.java
-  Implemented a new API to get the geolocation token
Tested with Postman and TestContainers
=> Geolocation token API

openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/enums/DocumentTypeEnum.java, src/main/java/it/gov/pagopa/cgn/portal/facade/DocumentFacade.java, src/test/java/it/gov/pagopa/cgn/portal/controller/DocumentApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/facade/DocumentFacadeTest.java
- Added missing 400 error code
Tested with Postman
=> Added missing 400 error code

src/main/resources/db/migration/R__create_offline_merchant_materialized_view.sql, src/main/resources/db/migration/R__create_online_merchant_materialized_view.sql
- Updated materialized view to manage possible empty profile name
Bugfix
=> Added coalesce to manage empty profile name

src/main/resources/db/migration/R__create_offline_merchant_materialized_view.sql, src/main/resources/db/migration/R__create_online_merchant_materialized_view.sql, src/main/resources/db/migration/V017__add_index_on_materialized_view.sql, src/main/resources/db/migration/V017__create_extension_pg_trgm.sql
- Added indexes to improve search API performance
=> Added indexes to improve search API performance

openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/DocumentService.java, src/main/resources/db/migration/V019__alter_discount_value_nullable.sql, src/main/resources/db/migration/V019_alter_discount_value_nullable.sql, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/DocumentServiceTest.java
This PR allows to NOT set a discount value on discounts, since there are cases with a not enumerable discounts.
=> [#PE-176] Allow nullable discount value

openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountEntity.java, src/main/resources/db/migration/V020__alter_discount_value_range.sql, src/test/java/it/gov/pagopa/cgn/portal/service/DocumentServiceTest.java
This PR allows to set a discount value within 1-100 range.
=> [#PE-179] Change discount value range to 1-100

local.session.sql, openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/annotation/CheckAddresses.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/CommonProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/model/AddressEntity.java, src/main/java/it/gov/pagopa/cgn/portal/model/ProfileEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/ProfileService.java, src/main/java/it/gov/pagopa/cgn/portal/validator/CheckAddressesValidator.java, src/main/resources/db/migration/R__create_offline_merchant_materialized_view.sql, src/main/resources/db/migration/V018__create_all_national_addresses.sql, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/profile/CreateProfileApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/converter/profile/UpdateProfileConverterTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/ProfileServiceTest.java
This PR is related to https://github.com/pagopa/cgn-onboarding-portal-frontend/pull/121
=> [#PE-174] Add all National addresses with migration

src/main/java/it/gov/pagopa/cgn/portal/enums/DiscountCodeTypeEnum.java, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountBucketCode.java, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountBucketCodeEntity.java, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountEntity.java, src/main/java/it/gov/pagopa/cgn/portal/repository/DiscountBucketCodeRepository.java, src/main/java/it/gov/pagopa/cgn/portal/repository/custom/DiscountBucketCodeRepositoryCustom.java, src/main/java/it/gov/pagopa/cgn/portal/repository/custom/DiscountBucketCodeRepositoryCustomImpl.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/resources/db/migration/V027__add_discount_code_type_enum_bucket_value copy.sql, src/main/resources/db/migration/V028__create_discount_bucket_code_table.sql, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/discount/DiscountApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
Add model for bucket codes discount mod.
=> [#PE-207] Add Model for Codes bucket

openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/discount/CreateDiscountConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/discount/DiscountConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/discount/UpdateDiscountConverter.java, src/main/java/it/gov/pagopa/cgn/portal/model/DiscountEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/resources/db/migration/V030__add_discount_eyca_flag.sql, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/DiscountServiceTest.java
We need to make discounts visible on eyca.
We added a flag during discount creation and update.
=> [#PE-202][#PE-203] Added visibleOnEyca flag to discounts

src/main/java/it/gov/pagopa/cgn/portal/SchedulerRunner.java, src/main/java/it/gov/pagopa/cgn/portal/config/ConfigProperties.java, src/main/java/it/gov/pagopa/cgn/portal/repository/BucketCodeLoadRepository.java, src/main/java/it/gov/pagopa/cgn/portal/repository/DiscountBucketCodeSummaryRepository.java, src/main/java/it/gov/pagopa/cgn/portal/scheduler/CheckAvailableDiscountBucketCodesJob.java, src/main/java/it/gov/pagopa/cgn/portal/scheduler/JobScheduler.java, src/main/java/it/gov/pagopa/cgn/portal/scheduler/SuspendDiscountsWithoutAvailableBucketCodesJob.java, src/main/java/it/gov/pagopa/cgn/portal/service/BucketService.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/resources/application.properties, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/scheduler/SuspendDiscountsWithoutAvailableBucketCodesJobTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/BucketServiceTest.java
=> [#PE-245] Job to suspend discounts after given days without bucket

openapi/backoffice/openapi.yaml, openapi/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/backoffice/approved/BackofficeApprovedAgreementProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/backoffice/approved/BackofficeApprovedDiscountConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/CommonProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/CreateProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/ProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/converter/profile/UpdateProfileConverter.java, src/main/java/it/gov/pagopa/cgn/portal/enums/SupportTypeEnum.java, src/main/java/it/gov/pagopa/cgn/portal/model/ProfileEntity.java, src/main/resources/db/migration/V043__add_support_columns.sql, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/controller/profile/CreateProfileApiTest.java
The "code duplication" sonarcloud issue is "fake". Code is the same, but packages are different.
=> [#IOCIT-32] Operators support channel

src/main/resources/db/migration/R__create_offline_merchant_materialized_view.sql, src/main/resources/db/migration/R__create_online_merchant_materialized_view.sql, src/main/resources/db/migration/R__create_published_product_category_materialized_view.sql
This should let Discounts to expire at 23:59:59 instead of 00:00:00
=> [#IOCIT-133] Modified CURRENT_TIMESTAMP and NOW() in CURRENT_DATE

src/main/resources/templates/pdf/pe-adhesion-request.html, src/main/resources/templates/pdf/pe-agreement.html, src/test/java/it/gov/pagopa/cgn/portal/service/DocumentServiceTest.java
New version templates for pe-agreement.html and pe-adhesion-request.html
=> Pe-354 new HTML templates for agreement and adhesion

src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java
modified message for running out of discount codes
=> modified message for running out of discount codes

src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationFacade.java, src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationService.java, src/main/java/it/gov/pagopa/cgn/portal/email/EmailParams.java, src/test/java/it/gov/pagopa/cgn/portal/service/EmailNotificationServiceTest.java
Pe 378 - added department as CC recipient for notification from Portal to Merchant referent
=> Pe 378 - added department as CC recipient for notification from Portal to Merchant referent

src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/test/java/it/gov/pagopa/cgn/portal/facade/BackofficeExportFacadeTest.java
Modified EXPIRED label logic - applyable only to dicounts in status PUBLISHED and having expiration date before the present day
Added two extra columns to the file - Profile id and Discount id
=> Modified export CGN file service

src/main/java/it/gov/pagopa/cgn/portal/service/ProfileService.java
Added SupportValue e SupportType to Profile update logic
=> [PE-456] Added SupportValue e SupportType to Profile update logic

src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/resources/db/migration/R__create_offline_merchant_materialized_view.sql, src/main/resources/db/migration/R__create_online_merchant_materialized_view.sql
We need to discriminate which categories have new discounts.
=> [#PE-467] Modified views to have categories that have new discounts

src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java
added log when eyca data export is empty
=> Check empty data with log

src/main/java/it/gov/pagopa/cgn/portal/converter/DataExportEycaConverter.java, src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java
Fix - sending only active opportunities
=> Fix - sending only active opportunities

src/main/resources/application.properties
deleted property
spring.quartz.enabled
changed value of property 
eyca.export.enabled
=> fixed scheduler properties

src/main/java/it/gov/pagopa/cgn/portal/model/EycaDataExportViewEntity.java, src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java
Added log for EYCA activity, key string  <<EYCA_LOG>> helps find the logs for eyca export
=> Added log for EYCA activity

src/main/java/it/gov/pagopa/cgn/portal/converter/DataExportEycaConverter.java
fill null data of locations with blank string
=> fill null data of locations with blank string

src/main/java/it/gov/pagopa/cgn/portal/config/JacksonConfiguration.java, src/test/java/it/gov/pagopa/cgn/portal/controller/discount/DiscountApiTest.java
=> Reverting jackson serializer

src/main/java/it/gov/pagopa/cgn/portal/config/JacksonConfiguration.java, src/test/java/it/gov/pagopa/cgn/portal/controller/discount/DiscountApiTest.java
changed jackson config to customize the default mapper
=> changed jackson config to customize the default mapper

openapi/eyca-data-export/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/converter/DataExportEycaConverter.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/EycaExportServiceTest.java
FIxed converter and api generated class
=> FIxed converter and api generated class

openapi/eyca-data-export/openapi.yaml
=> changed call from PUT to POST

src/main/java/it/gov/pagopa/cgn/portal/converter/DataExportEycaConverter.java, src/main/java/it/gov/pagopa/cgn/portal/enums/DiscountCodeTypeEnum.java, src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/EycaExportServiceTest.java
Fix - added discount codes for EYCA
=> Fix - added discount codes for EYCA

src/main/java/it/gov/pagopa/cgn/portal/converter/referent/DataExportEycaWrapper.java, src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/EycaExportServiceTest.java
=> Eyca check data

src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java
=> FIX eyca export

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, pom.xml, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeAgreementServiceTest.java
Updated maven plugin version
Updated jdk to version 1.17
Updated jacoco to 0.8.8
Updated lombok to 1.18.22
Updated yaml for pipelines deploy and code review
Refactored two tests
=> [#PE-526] update onboarding portal backend to java 17 (or later)

Dockerfile
- Upgraded Java version on docker file
- adoptopenjdk is deprecated thus it was changed with eclipse-temurin
=> Updated FROM image in docker file

openapi/eyca-data-export/openapi.yaml, src/main/java/it/gov/pagopa/cgn/portal/service/ExportService.java, src/main/java/it/gov/pagopa/cgn/portal/service/EycaExportService.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java, src/test/java/it/gov/pagopa/cgn/portal/service/EycaExportServiceTest.java
=> Send delete to EYCA

src/main/java/it/gov/pagopa/cgn/portal/converter/DataExportEycaConverter.java, src/test/java/it/gov/pagopa/cgn/portal/TestUtils.java
Fix, - BUCKET live value not updated
=> Fix, - BUCKET live value not updated

src/main/java/it/gov/pagopa/cgn/portal/converter/AgreementConverter.java, src/main/java/it/gov/pagopa/cgn/portal/facade/BackofficeAttributeAuthorityFacade.java, src/main/java/it/gov/pagopa/cgn/portal/service/AttributeAuthorityService.java, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java, src/test/java/it/gov/pagopa/cgn/portal/controller/AgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/controller/backoffice/BackofficeAgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/controller/backoffice/BackofficeApprovedAgreementApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/controller/backoffice/BackofficeAttributeAuthorityOrganizationsApiTest.java, src/test/java/it/gov/pagopa/cgn/portal/converter/AgreementConverterTest.java, src/test/java/it/gov/pagopa/cgn/portal/converter/OrganizationWithReferentsPostConverterTest.java, src/test/java/it/gov/pagopa/cgn/portal/facade/BackofficeAttributeAuthorityFacadeTest.java, src/test/java/it/gov/pagopa/cgn/portal/facade/ProfileFacadeTest.java, src/test/java/it/gov/pagopa/cgn/portal/service/backoffice/BackofficeAgreementServiceTest.java
Insertion of EntityType in responses
=> Pe 534 be fix su campo entity type mancante nelle chiamate

src/main/resources/db/migration/R__create_merchant_materialized_view.sql
Created a new materialized view to allow merchant search on all merchants.
=> [#PE-729] Created new merchant materialized view

src/main/java/it/gov/pagopa/cgn/portal/facade/ProfileFacade.java
When changes salesChennel or discountCodeType
=> Upgraded copy for suspended discounts

src/main/java/it/gov/pagopa/cgn/portal/converter/UpdateDataExportEycaWrapperConverter.java, src/main/resources/db/migration/R__create_eyca_data_export_view.sql
=> fix for esclude empty landing page url

src/main/java/it/gov/pagopa/cgn/portal/email/EmailNotificationFacade.java, src/test/java/it/gov/pagopa/cgn/portal/facade/EmailNotificationFacadeTest.java
=> Fixed missing context placeholder

src/main/java/it/gov/pagopa/cgn/portal/facade/ProfileFacade.java, src/main/java/it/gov/pagopa/cgn/portal/service/DiscountService.java, src/main/java/it/gov/pagopa/cgn/portal/service/ProfileService.java, src/test/java/it/gov/pagopa/cgn/portal/IntegrationAbstractTest.java
- added views update after profile update
- cleaned some code
=> [#PE-954] Fixed views update after profile update
